export const GAME_CONSTANTS = {
  MAX_OVERMAGE_FACTOR: 1.01, // 1% above max = overmage threshold
  SINK_DECAY_RATE: 0.1,
  BASE_SUCCESS_RATE_BELOW_MAX: 0.95,
  BASE_SUCCESS_RATE_AT_MAX: 0.65,
  BASE_SUCCESS_RATE_OVERMAGE: 0.40,
  MONTE_CARLO_DEFAULT_ITERATIONS: 10000,
  MAX_STAT_HISTORY: 100,
} as const;
